---
apiVersion: v1
kind: Namespace
metadata:
  name: loadtester
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtester
  namespace: loadtester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtester
  template:
    metadata:
      labels:
        app: loadtester
    spec:
      containers:
      - name: loadtester
        image: ghcr.io/mirceanton/loadtester
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "100m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: loadtester
  namespace: loadtester
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loadtester
---
apiVersion: v1
kind: Service
metadata:
  name: loadtester
  namespace: loadtester
spec:
  selector:
    app: loadtester
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loadtester
  namespace: loadtester
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
spec:
  ingressClassName: nginx
  rules:
  - host: loadtester.home.chitzu.ro
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loadtester
            port:
              number: 80